// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
wowReInitor(jQuery("#wowslider-container1"),{effect:"stack",prev:"",next:"",duration:10*100,delay:20*100,width:960,height:360,autoPlay:true,stopOnHover:true,loop:false,bullets:true,caption:true,controls:true,logo:"engine1/loading.gif",images:0});